ZavrsniRad-master/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolovniAutomobiliZavrsniRad.Models;

namespace PolovniAutomobiliZavrsniRad.Controllers
{
    [Authorize]
    public class AspNetUsersController : Controller
    {
        private readonly AutoContext db;

        public AspNetUsersController(AutoContext context)
        {
            db = context;
        }

        // GET: AspNetUsers
        public async Task<IActionResult> Index()
        {
            return View(await db.AspNetUsers.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> DodajMarkuModelTip(int ModelId = 0, int MarkaId = 0, string NoviTip = "", string NovaMarkaModel = "")
        {
            if (NovaMarkaModel!=" ")
            {
                NovaMarkaModel = NovaMarkaModel.First().ToString().ToUpper() + String.Join("", NovaMarkaModel.Skip(1)).ToLower();
                if (MarkaId == 0)
                {
                    try
                    {
                        Marka m1 = new Marka
                        {
                            Naziv = NovaMarkaModel
                        };
                        db.Marke.Add(m1);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception)
                    {

                        ViewBag.Greska="Doslo je do greske prilikom cuvanja Marke";
                    }
                }
                if (MarkaId!=0 && ModelId==0)
                {
                    try
                    {
                        Modeli m1 = new Modeli
                        {
                            MarkaId=MarkaId,
                            Naziv = NovaMarkaModel
                        };
                        db.Models.Add(m1);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception)
                    {
                        ViewBag.Greska = "Doslo je do greske prilikom cuvanja Modela";
                    }
                }
            }
            if (NoviTip!="")
            {
                NoviTip = NoviTip.First().ToString().ToUpper() + String.Join("", NoviTip.Skip(1)).ToLower();
                try
                {
                    TipVozila t1 = new TipVozila
                    {
                        Naziv = NoviTip
                    };
                    db.TipoviVozila.Add(t1);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception)
                {
                    ViewBag.Greska = "Doslo je do greske prilikom cuvanja Tipa vozila";                    
                }
                
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: AspNetUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            //var aspNetUser = await db.AspNetUsers
            //    .FirstOrDefaultAsync(m => m.Id == id);
            //if (aspNetUser == null)
            //{
            //    return NotFound();
            //}
            //ViewBag.Ime = aspNetUser.Ime;
            //ViewBag.Prezime = aspNetUser.Prezime;
            //ViewBag.Telefon = aspNetUser.Telefon;
            //ViewBag.Grad = aspNetUser.Grad;
            //ViewBag.Adresa = aspNetUser.Adresa;
            //return View();
            ViewBag.Marka = new SelectList(db.Marke, "MarkaId", "Naziv");
            ViewBag.Tip = new SelectList(db.TipoviVozila, "TipVozilaId", "Naziv");

            if (id == null)
            {
                return NotFound();
            }

            var aspNetUser = await db.AspNetUsers.FindAsync(id);
            if (aspNetUser == null)
            {
                return NotFound();
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount,Adresa,Grad,Ime,Prezime,Telefon")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Add(aspNetUser);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aspNetUser = await db.AspNetUsers.FindAsync(id);
            if (aspNetUser == null)
            {
                return NotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount,Adresa,Grad,Ime,Prezime,Telefon")] AspNetUser aspNetUser)
        {
            if (id != aspNetUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(aspNetUser);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AspNetUserExists(aspNetUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Details",id);
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aspNetUser = await db.AspNetUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspNetUser == null)
            {
                return NotFound();
            }

            return View(aspNetUser);
        }

        // POST: AspNetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var aspNetUser = await db.AspNetUsers.FindAsync(id);
            db.AspNetUsers.Remove(aspNetUser);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspNetUserExists(string id)
        {
            return db.AspNetUsers.Any(e => e.Id == id);
        }
    }
}

ZavrsniRad-master/Controllers/KomentarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolovniAutomobiliZavrsniRad.Models;

namespace PolovniAutomobiliZavrsniRad.Controllers
{
    [Authorize]
    public class KomentarController : Controller
    {
        private readonly AutoContext db;

        public KomentarController(AutoContext context)
        {
            db = context;
        }

        // GET: Komentar
        [AllowAnonymous]
        public IActionResult Index(int? id)
        {
            IEnumerable<Komentar> listaKomentara = db.Kometari;
            if (id != null)
            {
                ViewBag.VoziloId = id;
                listaKomentara = listaKomentara.Where(k => k.VoziloId == id);
            }
            else
            {
                ViewBag.Komentar = "Nema komentara";
            }
            return View(listaKomentara);
        }

        // GET: Komentar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Kometari
                .Include(k => k.Vozilo)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        // GET: Komentar/Create
        //public IActionResult Create()
        //{
        //    ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza");
        //    return View();
        //}

        // POST: Komentar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int VoziloId,string KorisnikId,string Korisnik,string Opis)
        {
            if (ModelState.IsValid)
            {
                Komentar k1 = new Komentar
                {
                    VoziloId = VoziloId,
                    KorisnikId = KorisnikId,
                    Korisnik = Korisnik,
                    Opis = Opis
                };
                db.Kometari.Add(k1);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
            //if (ModelState.IsValid)
            //{
            //    db.Add(komentar);
            //    await db.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //return RedirectToAction(nameof(Index));
        }

        // GET: Komentar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var komentar = await db.Kometari.FindAsync(id);
            if (komentar == null)
            {
                return NotFound();
            }
            ViewBag.Opis = komentar.Opis;
            ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza", komentar.VoziloId);
            return View(komentar);
        }

        // POST: Komentar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KomentarId,VoziloId,KorisnikId,Korisnik,Opis")] Komentar komentar)
        {
            if (id != komentar.KomentarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(komentar);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KomentarExists(komentar.KomentarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza", komentar.VoziloId);
            return View(komentar);
        }

        // GET: Komentar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Kometari
                .Include(k => k.Vozilo)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        // POST: Komentar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var komentar = await db.Kometari.FindAsync(id);
            db.Kometari.Remove(komentar);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KomentarExists(int id)
        {
            return db.Kometari.Any(e => e.KomentarId == id);
        }
    }
}

ZavrsniRad-master/Views/Profil/Create.cshtml
@model Vozilo
@inject UserManager<ApplicationUser> um
@{
    ViewData["Title"] = "Create";
    var korisnik = await um.GetUserAsync(User);
}

<h1>Dodaj Oglas</h1>

<h4>Oglas</h4>
<hr />
<div class="row">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    @*<label asp-for="MarkaId" class="control-label">Marka</label>*@
                    <select id="Select1" asp-for="MarkaId" class="form-control" asp-items="@ViewBag.Marka">
                        <option value="0">--Izaberite Marku--</option>
                    </select>
                </div>
                <div id="div1" class="form-group col-md-4">
                    <select class="form-control">
                        <option value="0">--Izaberite Model--</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    @*<label asp-for="TipVozilaId" class="control-label"></label>*@
                    <select asp-for="TipVozilaId" class="form-control" asp-items="@ViewBag.Tip">
                        <option value="0">--Izaberite Kategoriju--</option>
                    </select>
                </div>
            </div>

            <div class="form-row" hidden>               
                <div class="form-group">
                    <input asp-for="KorisnikId" class="form-control" value="@korisnik.Id" />
                    <span asp-validation-for="KorisnikId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label asp-for="Kubikaza" class="control-label"></label>
                    <input asp-for="Kubikaza" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" class="form-control" />
                    <span asp-validation-for="Kubikaza" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Snaga" class="control-label"></label>
                    <input asp-for="Snaga" class="form-control" />
                    <span asp-validation-for="Snaga" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Kilometraza" class="control-label"></label>
                    <input type="text" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" asp-for="Kilometraza" class="form-control" />
                    <span asp-validation-for="Kilometraza" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label asp-for="Pogon" class="control-label"></label>
                    <input asp-for="Pogon" class="form-control" />
                    <span asp-validation-for="Pogon" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Menjac" class="control-label"></label>
                    <input asp-for="Menjac" class="form-control" />
                    <span asp-validation-for="Menjac" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="BrojBrzina" class="control-label">Broj Brzina</label>
                    <input type="text" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" asp-for="BrojBrzina" class="form-control" />
                    <span asp-validation-for="BrojBrzina" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label asp-for="Cena" class="control-label">Cena</label>
                    <input type="text" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" asp-for="Cena" class="form-control" />
                    <span asp-validation-for="Cena" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label for="File1" class="control-label">Odaberi sliku</label>
                    <input id="File1" type="file" name="odabranaSlika" class="form-control" onchange="PrikaziSliku()" accept=".jpg, .gif, .bmp" />
                </div>
                <div class="form-group col-md-4">
                    <img src="" id="img1" width="200" height="150" />
                </div>
            </div>
            
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label asp-for="Opis" class="control-label"></label>
                    <textarea asp-for="Opis" cols="30" rows="10" class="form-control"></textarea>
                    <span asp-validation-for="Opis" class="text-danger"></span>
                </div>
            </div>
            
            <div class="form-row">
                <div class="form-group">
                    <input type="submit" value="Kreiraj oglas" class="btn btn-primary" style="padding-right:5px;" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-info" style="padding-left:5px;">Nazad na oglase</a>

                </div>
            </div>
            
        </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    //prikazivanje slike
    function PrikaziSliku() {
            var File1 = document.getElementById("File1");
            var img1 = document.getElementById("img1");
            var fajlSlike = File1.files[0];
            if (fajlSlike != null > 0 && fajlSlike.type.match(/image.*/)) {
                var reader = new FileReader();
                reader.readAsDataURL(fajlSlike);
                reader.onload = function () {
                    img1.src = reader.result;
                };
            }
            else {
                img1.setAttribute("src", "");
            }
        }
        function Validacija() {
            var src = $("#img1").attr("src");
            if (src == "") {
                $("#p1").html("Odaberite sliku");
                return false;
            }
            else {
                return true;
            }
        }
    
    

    //Prikazivanje modela
    $(document).ready(function () {
            $("#Select1").change(function () {
                var markaId = $(this).val();
                $.ajax({
                    type: "POST",
                    url: "/Home/PrikaziModel/",
                    dataType: "html",
                    data: { "markaId": markaId },
                    success: function (model) {
                        $("#div1").empty();
                        $("#div1").html(model);
                    }
                });
            });
        });
</script>

}

ZavrsniRad-master/Views/Profil/Delete.cshtml
@model Vozilo

<div class="container">
    <h2>@Model.Marka.Naziv  @Model.Modeli.Naziv</h2>
    <div class="row">
        <div class="col-md-4 mb-5">
            @*<img width="250" style="padding:5px" height="200" src="@($"/Profil/CitajSliku/{Model.VoziloId}")" alt="Slika" />*@
            <img style="padding:5px;width:75%;height:75%" src="@($"/Profil/CitajSliku/{Model.VoziloId}")" alt="Slika" />

            <br />
            <label for="opis1" class="control-label">Opis</label>
            <textarea readonly id="opsi1" cols="30" style="height:160px" rows="10" class="form-control">@Model.Opis</textarea>
        </div>
        <div class="col-md-4 mt-5 mb-5">
            <table class="table table-striped border">
                <tr>
                    <th>Kubikaza</th>
                    <td>@Model.Kubikaza</td>
                </tr>
                <tr>
                    <th>Snaga</th>
                    <td>@Model.Snaga</td>
                </tr>
                <tr>
                    <th>Kilometraza</th>
                    <td>@Model.Kilometraza</td>
                </tr>
                <tr>
                    <th>Pogon</th>
                    <td>@Model.Pogon</td>
                </tr>
                <tr>
                    <th>Menjac</th>
                    <td>@Model.Menjac</td>
                </tr>
                <tr>
                    <th>Broj Brzina</th>
                    <td>@Model.BrojBrzina</td>
                </tr>
                <tr>
                    <th>Cena</th>
                    <td>@Model.Cena e</td>
                </tr>
                <tr>
                    <th>Tip Vozila</th>
                    <td>@Model.TipVozila.Naziv</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4 mt-5">
            <form asp-action="Delete">
                <input type="hidden" asp-for="VoziloId" />
                <div class="form-group">
                    <input type="submit" value="Obrisi" class="btn btn-danger form-control" />
                </div>
                <a class="btn btn-info form-control" asp-action="Index" asp-controller="Home">Odustani</a>
            </form>
        </div>
    </div>
</div>

ZavrsniRad-master/Views/Profil/Details.cshtml
@model Vozilo

@{
    ViewData["Title"] = "Details";
}


<div class="container">
    <h2>@Model.Marka.Naziv  @Model.Modeli.Naziv</h2>
    <div class="row">
        <div class="col-md-4 mb-5">
            @*<img width="250" style="padding:5px" height="200" src="@($"/Profil/CitajSliku/{Model.VoziloId}")" alt="Slika" />*@
            <img style="padding:5px;width:75%;height:75%" src="@($"/Profil/CitajSliku/{Model.VoziloId}")" alt="Slika" />

            <br />
            <label for="opis1" class="control-label">Opis</label>
            <textarea readonly id="opsi1" cols="30" style="height:160px" rows="10" class="form-control">@Model.Opis</textarea>
        </div>
        <div class="col-md-4 mt-5 mb-5">
            <table class="table table-striped border">
                <tr>
                    <th>Kubikaza</th>
                    <td>@Model.Kubikaza</td>
                </tr>
                <tr>
                    <th>Snaga</th>
                    <td>@Model.Snaga</td>
                </tr>
                <tr>
                    <th>Kilometraza</th>
                    <td>@Model.Kilometraza</td>
                </tr>
                <tr>
                    <th>Pogon</th>
                    <td>@Model.Pogon</td>
                </tr>
                <tr>
                    <th>Menjac</th>
                    <td>@Model.Menjac</td>
                </tr>
                <tr>
                    <th>Broj Brzina</th>
                    <td>@Model.BrojBrzina</td>
                </tr>
                <tr>
                    <th>Cena</th>
                    <td>@Model.Cena e</td>
                </tr>
                <tr>
                    <th>Tip Vozila</th>
                    <td>@Model.TipVozila.Naziv</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4 mt-5">
            <a asp-route-id="@Model.VoziloId" asp-action="Index" style="padding:5px 0px 5px 0px;" asp-controller="Komentar" class="btn btn-block btn-info">Prikazi Komentare</a>
            <a asp-route-id="@ViewBag.KorisnikId" asp-action="Details" asp-controller="AspNetUsers" style="padding:5px 0px 5px 0px;" class="btn btn-block btn-secondary">Pogledajte jos oglasa od korisnika.</a>
            <br />
            <div>
                <span>Informacije o korisniku</span>
                <table class="table table-info">
                    <tr>
                        <th>Ime</th>
                        <td>@ViewBag.Ime</td>
                    </tr>
                    <tr>
                        <th>Prezime</th>
                        <td>@ViewBag.Prezime</td>
                    </tr>
                    <tr>
                        <th>Telefon</th>
                        <td>@ViewBag.Telefon</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>