ZavrsniRad-master/Controllers/KomentarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolovniAutomobiliZavrsniRad.Models;

namespace PolovniAutomobiliZavrsniRad.Controllers
{
    [Authorize]
    public class KomentarController : Controller
    {
        private readonly AutoContext db;

        public KomentarController(AutoContext context)
        {
            db = context;
        }

        // GET: Komentar
        [AllowAnonymous]
        public IActionResult Index(int? id)
        {
            IEnumerable<Komentar> listaKomentara = db.Kometari;
            if (id != null)
            {
                ViewBag.VoziloId = id;
                listaKomentara = listaKomentara.Where(k => k.VoziloId == id);
            }
            else
            {
                ViewBag.Komentar = "Nema komentara";
            }
            return View(listaKomentara);
        }

        // GET: Komentar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Kometari
                .Include(k => k.Vozilo)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        // GET: Komentar/Create
        //public IActionResult Create()
        //{
        //    ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza");
        //    return View();
        //}

        // POST: Komentar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int VoziloId,string KorisnikId,string Korisnik,string Opis)
        {
            if (ModelState.IsValid)
            {
                Komentar k1 = new Komentar
                {
                    VoziloId = VoziloId,
                    KorisnikId = KorisnikId,
                    Korisnik = Korisnik,
                    Opis = Opis
                };
                db.Kometari.Add(k1);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
            //if (ModelState.IsValid)
            //{
            //    db.Add(komentar);
            //    await db.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //return RedirectToAction(nameof(Index));
        }

        // GET: Komentar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var komentar = await db.Kometari.FindAsync(id);
            if (komentar == null)
            {
                return NotFound();
            }
            ViewBag.Opis = komentar.Opis;
            ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza", komentar.VoziloId);
            return View(komentar);
        }

        // POST: Komentar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KomentarId,VoziloId,KorisnikId,Korisnik,Opis")] Komentar komentar)
        {
            if (id != komentar.KomentarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(komentar);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KomentarExists(komentar.KomentarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VoziloId"] = new SelectList(db.Vozila, "VoziloId", "Kilometraza", komentar.VoziloId);
            return View(komentar);
        }

        // GET: Komentar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = await db.Kometari
                .Include(k => k.Vozilo)
                .FirstOrDefaultAsync(m => m.KomentarId == id);
            if (komentar == null)
            {
                return NotFound();
            }

            return View(komentar);
        }

        // POST: Komentar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var komentar = await db.Kometari.FindAsync(id);
            db.Kometari.Remove(komentar);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KomentarExists(int id)
        {
            return db.Kometari.Any(e => e.KomentarId == id);
        }
    }
}

ZavrsniRad-master/Controllers/ProfilController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PolovniAutomobiliZavrsniRad.Models;

namespace PolovniAutomobiliZavrsniRad.Controllers
{
    [Authorize]
    public class ProfilController : Controller
    {
        private readonly AutoContext db;
        public ProfilController(AutoContext _db)
        {
            db = _db;
        }
        [AllowAnonymous]
        public FileContentResult CitajSliku(int? id)
        {
            if (id == null)
            {
                return null;
            }
            Vozilo v1 = db.Vozila.Find(id);
            if (v1 == null)
            {
                return null;
            }
            return File(v1.Slika, v1.SlikaTip);
        }

        // GET: Profil
        public ActionResult Index()
        {
            return View();
        }

        // GET: Profil/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await db.Vozila
                .Include(v => v.Marka)
                .Include(v => v.Modeli)
                .Include(v => v.TipVozila)
                .Include(v => v.Komentars)
                .FirstOrDefaultAsync(m => m.VoziloId == id);
            string korisnikId = vozilo.KorisnikId;           
            try
            {
                var korisnik = await db.AspNetUsers.FindAsync(korisnikId);
                ViewBag.Ime = korisnik.Ime;
                ViewBag.Prezime = korisnik.Prezime;
                ViewBag.Telefon = korisnik.Telefon;
                ViewBag.KorisnikId = korisnikId;
            }
            catch (Exception)
            {
                ViewBag.Greska="Doslo je do greske";
            }
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // GET: Profil/Create
        public ActionResult Create()
        {
            ViewBag.Marka = new SelectList(db.Marke, "MarkaId", "Naziv");
            ViewBag.Tip = new SelectList(db.TipoviVozila, "TipVozilaId", "Naziv");
            return View();
        }

        // POST: Profil/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VoziloId,MarkaId,ModelId,TipVozilaId,KorisnikId,Kubikaza,Snaga,Kilometraza,Pogon,Menjac,BrojBrzina,Cena,Slika,SlikaTip,Opis")]
        Vozilo vozilo, IFormFile odabranaSlika)
        {
            if (odabranaSlika == null)
            {
                ModelState.AddModelError("FajlSlike", "Niste");
            }
            if (ModelState.IsValid)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    await odabranaSlika.CopyToAsync(ms);
                    vozilo.Slika = ms.ToArray();
                }
                vozilo.SlikaTip = odabranaSlika.ContentType;
                db.Add(vozilo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(vozilo);
        }
        
        // GET: Profil/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await db.Vozila.FindAsync(id);
            if (vozilo == null)
            {
                return NotFound();
            }
            ViewData["MarkaId"] = new SelectList(db.Marke, "MarkaId", "Naziv", vozilo.MarkaId);
            ViewData["ModelId"] = new SelectList(db.Models, "ModelId", "Naziv", vozilo.ModelId);
            ViewData["TipVozilaId"] = new SelectList(db.TipoviVozila, "TipVozilaId", "Naziv", vozilo.TipVozilaId);
            return View(vozilo);
        }

        // POST: Profil/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VoziloId,MarkaId,ModelId,TipVozilaId,KorisnikId,Kubikaza,Snaga,Kilometraza,Pogon,Menjac,BrojBrzina,Cena,Slika,SlikaTip,Opis")] Vozilo vozilo, IFormFile odabranaSlika)
        {

            if (id != vozilo.VoziloId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        await odabranaSlika.CopyToAsync(ms);
                        vozilo.Slika = ms.ToArray();
                    }
                    vozilo.SlikaTip = odabranaSlika.ContentType;
                    db.Update(vozilo);
                    await db.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoziloExists(vozilo.VoziloId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            ViewData["MarkaId"] = new SelectList(db.Marke, "MarkaId", "Naziv", vozilo.MarkaId);
            ViewData["ModelId"] = new SelectList(db.Models, "ModelId", "Naziv", vozilo.ModelId);
            ViewData["TipVozilaId"] = new SelectList(db.TipoviVozila, "TipVozilaId", "Naziv", vozilo.TipVozilaId);
            return View(vozilo);
        }

        private bool VoziloExists(int id)
        {
            return db.Vozila.Any(e => e.VoziloId == id);
        }

        //GET: Profil/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilo = await db.Vozila
                .Include(v => v.Marka)
                .Include(v => v.Modeli)
                .Include(v => v.TipVozila)
                .FirstOrDefaultAsync(m => m.VoziloId == id);
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // POST: Profil/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var vozilo = await db.Vozila.FindAsync(id);
            db.Vozila.Remove(vozilo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
    }
}

ZavrsniRad-master/Views/Home/AdminSistema.cshtml
@{
    ViewData["Title"] = "AdminSistema";
}

    <h2>@ViewBag.Poruka</h2>

ZavrsniRad-master/Views/Home/Filtriraj.cshtml
@model IEnumerable<Vozilo>
@inject SignInManager<ApplicationUser> sm
@inject UserManager<ApplicationUser> um
@{
    var korisnik = await um.GetUserAsync(User);
}

@if (Model != null)
{
    @foreach (Vozilo v in Model)
    {
        <div class="col-md-4 col-xl-3 col-12 col-sm-6 mb-3">
            <div class="card bg-light" style="width:230px">
                <div class="card-header" style="padding:5px">
                    <a asp-action="Details" asp-controller="Profil" asp-route-id="@v.VoziloId">
                        <img width="200" style="padding:5px;margin-left:10px" height="150" src="@($"/Profil/CitajSliku/{v.VoziloId}")" alt="Slika" />
                    </a>
                </div>
                <div class="card-body">
                    <h5>Marka: @v.Marka.Naziv</h5>
                    <h5>Model: @v.Modeli.Naziv</h5>
                    <h5>Cena: @v.Cena e</h5>
                    <a asp-route-id="@v.VoziloId" asp-action="Index" asp-controller="Komentar" class="btn btn-block btn-info">Prikazi Komentare</a>
                    @if (sm.IsSignedIn(User))
                    {
                        @if (korisnik.Email == "admin@gmail.com")
                        {
                            <a asp-route-id="@v.VoziloId" asp-action="Delete" asp-controller="Profil" class="btn btn-block btn-danger">Obrisi Oglas</a>

                        }
                        @if (korisnik.Id == v.KorisnikId)
                        {
                            <a asp-route-id="@v.VoziloId" asp-action="Edit" asp-controller="Profil" class="btn btn-block btn-success">Promeni Oglas</a>
                            <a asp-route-id="@v.VoziloId" asp-action="Delete" asp-controller="Profil" class="btn btn-block btn-danger">Obrisi Oglas</a>
                        }
                    }
                </div>
            </div>
        </div>
    }
}
else
{
    <h2 class="text-danger">
        Nazalost nije postavljen ni jedan oglas!
    </h2>

}

ZavrsniRad-master/Views/Home/Index.cshtml
@model IEnumerable<Vozilo>
@inject SignInManager<ApplicationUser> sm
@inject UserManager<ApplicationUser> um
@{ 
    var korisnik = await um.GetUserAsync(User);
}
    <div class="container padding">
        <div class="row">
            @*<div class="col-md-3">*@
                <form asp-action="Filtriraj" asp-controller="Home" method="post" data-ajax="true" data-ajax-update="#prikazi">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <select id="Select1" name="MarkaId" asp-items="@ViewBag.Marka" class="form-control">
                                <option value="0">--Izaberi Marku--</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6" id="div1">
                            <select class="form-control">
                                <option value="0">--Izaberite Model--</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="min">Unesite minimalnu cenu</label>
                        <input class="form-control" type="text" placeholder="Minimalna cena" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" name="min" id="min" />
                    </div>
                    <div class="form-group">
                        <label for="max">Unesite maksimalnu cenu</label>
                        <input class="form-control" type="text" placeholder="Maksimalna cena" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" name="max" id="max" />
                    </div>
                    <input type="submit" class="btn btn-success" value="Posalji" />
                </form>
            @*</div>*@
        </div>
    </div>

<br class="my-4"/>
<br />
<div class="container">
    <div class="row" id="prikazi">
        @if (Model != null)
        {
            @foreach (Vozilo v in Model)
            {
                <div class="col-md-4 col-xl-3 col-12 col-sm-6 mb-3">
                    <div class="card bg-light" style="width:230px">
                        <div class="card-header" style="padding:5px">
                            <a asp-action="Details" asp-controller="Profil" asp-route-id="@v.VoziloId">
                                <img width="200" style="padding:5px;margin-left:10px" height="150" src="@($"/Profil/CitajSliku/{v.VoziloId}")" alt="Slika" />
                            </a>
                        </div>
                        <div class="card-body">
                            <h5>Marka: @v.Marka.Naziv</h5>
                            <h5>Model: @v.Modeli.Naziv</h5>
                            <h5>Cena: @v.Cena e</h5>
                            <a asp-route-id="@v.VoziloId" asp-action="Index" asp-controller="Komentar" class="btn btn-block btn-info">Prikazi Komentare</a>

                            @if (sm.IsSignedIn(User))
                            {
                                @if (korisnik.Email == "admin@gmail.com")
                                {
                                    <a asp-route-id="@v.VoziloId" asp-action="Delete" asp-controller="Profil" class="btn btn-block btn-danger">Obrisi Oglas</a>
                                }
                                @if (korisnik.Id == v.KorisnikId)
                                {
                                    <a asp-route-id="@v.VoziloId" asp-action="Edit" asp-controller="Profil" class="btn btn-block btn-success">Promeni Oglas</a>
                                    <a asp-route-id="@v.VoziloId" asp-action="Delete" asp-controller="Profil" class="btn btn-block btn-danger">Obrisi Oglas</a>
                                }
                            }
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h2 class="text-danger">
                Nazalost nije postavljen ni jedan oglas!
            </h2>

        }
    </div>
</div>






@section Scripts{

    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#Select1").change(function () {
                var markaId = $(this).val();
                $.ajax({
                    type: "POST",
                    url: "/Home/PrikaziModel/",
                    dataType: "html",
                    data: { "markaId": markaId },
                    success: function (model) {
                        $("#div1").empty();
                        $("#div1").html(model);
                    }
                });
            });
        });
    </script>
}

ZavrsniRad-master/Views/Home/Posalji.cshtml
@{
    ViewData["Title"] = "Posalji";
}

<div class="row">
    <div class="col-md-12">
        <div id="poruka" class="alert alert-info">@ViewBag.Poruka</div>
    </div>
    <div class="col-md-5">
        <form asp-action="Posalji" asp-controller="Home" method="post">
            <div class="form-group">
                <label for="TextIme">Ime:</label>
                <input type="text" name="ime" id="TextIme" class="form-control" autofocus required oninvalid="this.setCustomValidity('Unesite Vase Ime')" oninput="this.setCustomValidity('')">
            </div>
            <div class="form-group">
                <label for="TextPrezime">Prezime:</label>
                <input type="text" name="prezime" id="TextPrezime" class="form-control" required oninvalid="this.setCustomValidity('Unesite Vase Prezime')" oninput="this.setCustomValidity('')">
            </div>
            <div class="form-group">
                <label for="TextEmail">Email:</label>
                <input type="email" name="email" id="TextEmail" class="form-control" required oninvalid="this.setCustomValidity('Unesite Vasu email adresu')" oninput="this.setCustomValidity('')">
            </div>
            <div class="form-group mt-3">
                <label class="ta" for="TextPoruka">Poruka:</label>
                <textarea name="poruka" id="TextPoruka" cols="30" rows="10" class="form-control" required oninvalid="this.setCustomValidity('Unesite Vasu Poruku')" oninput="this.setCustomValidity('')"></textarea>
                <input type="submit" value="Posalji" class="btn btn-success form-group" style="margin-top: 5px !important;">
            </div>
        </form>
    </div>
    <div class="col-md-5 mt-4">
        <iframe src="https://www.google.com/maps/embed?pb=" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            if ($("#poruka").text() == "") {
                $("#poruka").attr("style", "display:none");
            }
        });
    </script>
}

ZavrsniRad-master/Views/Home/PrikaziModel.cshtml
    <select class="form-control" asp-items="@ViewBag.Model" name="ModelId">
        <option value="0">--Izaberite Model--</option>
    </select>